"""replace pdf_data blob with pdf_storage_key for R2 storage

Revision ID: 3d87fe9e49cb
Revises: 5a196cdaa0b7
Create Date: 2026-07-15 21:27:07.890280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d87fe9e49cb'
down_revision = '5a196cdaa0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_storage_key', sa.String(length=255), nullable=True))
        batch_op.drop_column('pdf_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_data', sa.BLOB(), nullable=True))
        batch_op.drop_column('pdf_storage_key')

    # ### end Alembic commands ###
