"""Add document_chunk table for RAG

Revision ID: 9cacd03cd2a1
Revises: ce7a585b3bec
Create Date: 2026-07-04 12:16:42.790734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cacd03cd2a1'
down_revision = 'ce7a585b3bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunk_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunk_document_id'))

    op.drop_table('document_chunk')
    # ### end Alembic commands ###
