"""Initial schema

Revision ID: ce7a585b3bec
Revises: 
Create Date: 2026-07-03 07:51:01.019380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7a585b3bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=128), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_achievement')
    )
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_user_id'), ['user_id'], unique=False)

    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('join_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_join_code'), ['join_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_class_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('flashcards', sa.JSON(), nullable=True),
    sa.Column('explainer_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_user_id'), ['user_id'], unique=False)

    op.create_table('class_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_student')
    )
    with op.batch_alter_table('class_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_membership_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_membership_student_id'), ['student_id'], unique=False)

    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_assignment', sa.Boolean(), nullable=False),
    sa.Column('join_code', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_join_code'), ['join_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_user_id'), ['user_id'], unique=False)

    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_session_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_session_user_id'), ['user_id'], unique=False)

    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('mcq_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('mcq_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('study_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_user_id'), ['user_id'], unique=False)

    op.create_table('class_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'quiz_id', name='uq_class_quiz')
    )
    with op.batch_alter_table('class_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_assignment_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_assignment_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('score_awarded', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_question_id'))
        batch_op.drop_index(batch_op.f('ix_answer_attempt_id'))

    op.drop_table('answer')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_quiz_id'))

    op.drop_table('question')
    with op.batch_alter_table('class_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_assignment_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_class_assignment_class_id'))

    op.drop_table('class_assignment')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_quiz_id'))

    op.drop_table('attempt')
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_session_document_id'))

    op.drop_table('study_session')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_join_code'))
        batch_op.drop_index(batch_op.f('ix_quiz_document_id'))

    op.drop_table('quiz')
    with op.batch_alter_table('class_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_membership_student_id'))
        batch_op.drop_index(batch_op.f('ix_class_membership_class_id'))

    op.drop_table('class_membership')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_user_id'))

    op.drop_table('document')
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_join_code'))

    op.drop_table('class')
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_user_id'))

    op.drop_table('achievement')
    op.drop_table('user')
    # ### end Alembic commands ###
